export const CONFIGURATION_SINGLE_REQUEST = "CONFIGURATION_SINGLE_REQUEST";
export const CONFIGURATION_SINGLE_SUCCESS = "CONFIGURATION_SINGLE_SUCCESS";
export const CONFIGURATION_SINGLE_FAIL = "CONFIGURATION_SINGLE_FAIL";
export const CONFIGURATION_SINGLE_RESET = "CONFIGURATION_SINGLE_RESET";

export const CONFIGURATION_UPDATE_REQUEST = "CONFIGURATION_UPDATE_REQUEST";
export const CONFIGURATION_UPDATE_SUCCESS = "CONFIGURATION_UPDATE_SUCCESS";
export const CONFIGURATION_UPDATE_FAIL = "CONFIGURATION_UPDATE_FAIL";
export const CONFIGURATION_UPDATE_RESET = "CONFIGURATION_UPDATE_RESET";
