export const IMPORT_STOCK_LIST_REQUEST = "IMPORT_STOCK_LIST_REQUEST";
export const IMPORT_STOCK_LIST_SUCCESS = "IMPORT_STOCK_LIST_SUCCESS";
export const IMPORT_STOCK_LIST_FAIL = "IMPORT_STOCK_LIST_FAIL";
export const IMPORT_STOCK_LIST_RESET = "IMPORT_STOCK_LIST_RESET";

export const IMPORT_STOCK_DETAILS_REQUEST = "IMPORT_STOCK_DETAILS_REQUEST";
export const IMPORT_STOCK_DETAILS_SUCCESS = "IMPORT_STOCK_DETAILS_SUCCESS";
export const IMPORT_STOCK_DETAILS_FAIL = "IMPORT_STOCK_DETAILS_FAIL";
export const IMPORT_STOCK_DETAILS_RESET = "IMPORT_STOCK_DETAILS_RESET";

export const IMPORT_STOCK_DELETE_REQUEST = "IMPORT_STOCK_DELETE_REQUEST";
export const IMPORT_STOCK_DELETE_SUCCESS = "IMPORT_STOCK_DELETE_SUCCESS";
export const IMPORT_STOCK_DELETE_FAIL = "IMPORT_STOCK_DELETE_FAIL";
export const IMPORT_STOCK_DELETE_RESET = "IMPORT_STOCK_DELETE_RESET";

export const IMPORT_STOCK_CREATE_REQUEST = "IMPORT_STOCK_CREATE_REQUEST";
export const IMPORT_STOCK_CREATE_SUCCESS = "IMPORT_STOCK_CREATE_SUCCESS";
export const IMPORT_STOCK_CREATE_FAIL = "IMPORT_STOCK_CREATE_FAIL";
export const IMPORT_STOCK_CREATE_RESET = "IMPORT_STOCK_CREATE_RESET";

export const IMPORT_STOCK_STATUS_REQUEST = "IMPORT_STOCK_STATUS_REQUEST";
export const IMPORT_STOCK_STATUS_SUCCESS = "IMPORT_STOCK_STATUS_SUCCESS";
export const IMPORT_STOCK_STATUS_FAIL = "IMPORT_STOCK_STATUS_FAIL";
export const IMPORT_STOCK_STATUS_RESET = "IMPORT_STOCK_STATUS_RESET";

export const IMPORT_STOCK_UPDATE_REQUEST = "IMPORT_STOCK_UPDATE_REQUEST";
export const IMPORT_STOCK_UPDATE_SUCCESS = "IMPORT_STOCK_UPDATE_SUCCESS";
export const IMPORT_STOCK_UPDATE_FAIL = "IMPORT_STOCK_UPDATE_FAIL";
export const IMPORT_STOCK_UPDATE_RESET = "IMPORT_STOCK_UPDATE_RESET";

export const IMPORT_STOCK_CANCEL_REQUEST = "IMPORT_STOCK_CANCEL_REQUEST";
export const IMPORT_STOCK_CANCEL_SUCCESS = "IMPORT_STOCK_CANCEL_SUCCESS";
export const IMPORT_STOCK_CANCEL_FAIL = "IMPORT_STOCK_CANCEL_FAIL";
export const IMPORT_STOCK_CANCEL_RESET = "IMPORT_STOCK_CANCEL_RESET";


export const REPORT_IMPORT_STOCK_REQUEST = "REPORT_IMPORT_CANCEL_REQUEST";
export const REPORT_IMPORT_STOCK_SUCCESS = "REPORT_IMPORT_CANCEL_SUCCESS";
export const REPORT_IMPORT_STOCK_FAIL = "REPORT_IMPORT_CANCEL_FAIL";
export const REPORT_IMPORT_STOCK_RESET = "REPORT_IMPORT_CANCEL_RESET";

export const HISTORY_INVENTORY_STOCK_REQUEST = "HISTORY_INVENTORY_CANCEL_REQUEST";
export const HISTORY_INVENTORY_STOCK_SUCCESS = "HISTORY_INVENTORY_CANCEL_SUCCESS";
export const HISTORY_INVENTORY_STOCK_FAIL = "HISTORY_INVENTORY_CANCEL_FAIL";
export const HISTORY_INVENTORY_STOCK_RESET = "HISTORY_INVENTORY_CANCEL_RESET";


export const REPORT_REVENUE_REQUEST = "REPORT_REVENUE_REQUEST";
export const REPORT_REVENUE_SUCCESS = "REPORT_REVENUE_SUCCESS";
export const REPORT_REVENUE_FAIL = "REPORT_REVENUE_FAIL";
export const REPORT_REVENUE_RESET = "REPORT_REVENUE_RESET";
